---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  labels:
    app.kubernetes.io/name: typescript-ex
  name: typescript-ex-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/otaviof/typescript-ex.git
    - name: revision
      value: main
