---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: typescript-ex
  labels:
    app.kubernetes.io/name: typescript-ex
spec:
  resources:
    - name: source
      type: git
  params:
    - name: OUTPUT
      type: string
      description: The image tag which will be built
  tasks:
    - name: build-and-test
      taskRef:
        name: typescript-ex-build-and-test
      resources:
        inputs:
          - name: source
            resource: source
    - name: image-build
      runAfter:
        - build-and-test
      params:
        - name: OUTPUT
          value: $(params.OUTPUT)
      taskRef:
        name: typescript-ex-build-image
      resources:
        inputs:
          - name: source
            resource: source