---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: typescript-ex
  name: typescript-ex
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: ci
      taskRef:
        name: typescript-ex-ci
      resources:
        inputs:
          - name: source
            resource: source
    - name: buildah
      runAfter:
        - ci
      params:
        - name: OUTPUT
          value: $(params.OUTPUT)
      taskRef:
        name: typescript-ex-buildah
      resources:
        inputs:
          - name: source
            resource: source
