---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: typescript-ex-build-image
  labels:
    app.kubernetes.io/name: typescript-ex
spec:
  resources:
    inputs:
      - name: source
        type: git
  params:
    - name: OUTPUT
      description: The image tag which will be built
  steps:
    - name: image-build
      image: quay.io/buildah/upstream:latest
      securityContext:
        runAsUser: 0
        privileged: true
      workingDir: /workspace/source
      script: |
        buildah bud --tag=$(params.OUTPUT) .
      volumeMounts:
        - name: containers-storage
          mountPath: /var/lib/containers
    - name: push
      image: quay.io/buildah/upstream:latest
      securityContext:
        runAsUser: 0
        privileged: true
      script: |
        buildah push --tls-verify=false $(params.OUTPUT)
      volumeMounts:
        - name: containers-storage
          mountPath: /var/lib/containers
  volumes:
    - name: containers-storage
      emptyDir: {}