---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: typescript-ex
  name: typescript-ex-ci
spec:
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: npm-ci
      image: docker.io/node:alpine
      workingDir: /workspace/source
      env:
        - name: CI
          value: "true"
      script: |
        npm install && \
        npm run build && \
        npm test
