---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: typescript-ex
  labels:
    app.kubernetes.io/name: typescript-ex
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: ci
      taskRef:
        name: typescript-ex-ci
      resources:
        inputs:
          - name: source
            resource: source
    - name: shipwright
      runAfter:
        - ci
      taskRef:
        apiVersion: shipwright.io/v1alpha1
        kind: Build
        name: typescript-ex
